{
 "title": "PWA",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pm2_cpu{name=\"default\"}/pm2_processes{name=\"default\"}",
     "legendFormat": "default"
    },
    {
     "expr": "pm2_cpu{name=\"blue\"}/pm2_processes{name=\"blue\"}",
     "legendFormat": "blue"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pm2_memory{name=\"default\"}/pm2_processes{name=\"default\"}",
     "legendFormat": "default"
    },
    {
     "expr": "pm2_memory{name=\"blue\"}/pm2_processes{name=\"blue\"}",
     "legendFormat": "blue"
    }
   ]
  },
  {
   "title": "SSR Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pm2_processes{name=\"default\"}",
     "legendFormat": "default"
    },
    {
     "expr": "pm2_processes{name=\"blue\"}",
     "legendFormat": "blue"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pm2_memory{name=\"default\"}/pm2_processes{name=\"default\"}",
     "legendFormat": "default"
    },
    {
     "expr": "pm2_memory{name=\"blue\"}/pm2_processes{name=\"blue\"}",
     "legendFormat": "blue"
    },
    {
     "expr": "pm2_memory{name=\"distributor\"}/pm2_processes{name=\"distributor\"}",
     "legendFormat": "distributor"
    },
    {
     "expr": "pm2_memory{name=\"prometheus\"}/pm2_processes{name=\"prometheus\"}",
     "legendFormat": "prometheus"
    }
   ]
  },
  {
   "title": "Requests 2m Window",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_status_code_counts{}[2m]))",
     "legendFormat": "ssr"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pm2_cpu{name=\"default\"}/pm2_processes{name=\"default\"}",
     "legendFormat": "default"
    },
    {
     "expr": "pm2_cpu{name=\"blue\"}/pm2_processes{name=\"blue\"}",
     "legendFormat": "blue"
    },
    {
     "expr": "pm2_cpu{name=\"distributor\"}/pm2_processes{name=\"distributor\"}",
     "legendFormat": "distributor"
    },
    {
     "expr": "pm2_cpu{name=\"prometheus\"}/pm2_processes{name=\"prometheus\"}",
     "legendFormat": "prometheus"
    }
   ]
  },
  {
   "title": "SSR Mean Render Time (0.95-quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{}[5m])) by (le))",
     "legendFormat": "ssr"
    }
   ]
  },
  {
   "title": "Process Restarts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pm2_process_restarts{name=\"default\"}",
     "legendFormat": "default"
    },
    {
     "expr": "pm2_process_restarts{name=\"blue\"}",
     "legendFormat": "blue"
    },
    {
     "expr": "pm2_process_restarts{name=\"distributor\"}",
     "legendFormat": "distributor"
    },
    {
     "expr": "pm2_process_restarts{name=\"prometheus\"}",
     "legendFormat": "prometheus"
    }
   ]
  },
  {
   "title": "SSR Status >=400",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_status_code_counts{status_code=~\"[4-5][0-9][0-9]\"}[2m]))"
    }
   ]
  },
  {
   "title": "Process: Default",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pm2_process_status_online{name=\"default\"})",
     "legendFormat": "online"
    },
    {
     "expr": "sum(pm2_process_status_launching{name=\"default\"})",
     "legendFormat": "launching"
    },
    {
     "expr": "sum(pm2_process_status_stopped{name=\"default\"})",
     "legendFormat": "stopped"
    },
    {
     "expr": "sum(pm2_process_status_errored{name=\"default\"})",
     "legendFormat": "errored"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pm2_process_restarts{name=\"default\"}[2m])",
     "legendFormat": "default"
    },
    {
     "expr": "increase(pm2_process_restarts{name=\"blue\"}[2m])",
     "legendFormat": "blue"
    }
   ]
  },
  {
   "title": "Process: Blue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pm2_process_status_online{name=\"blue\"})",
     "legendFormat": "online"
    },
    {
     "expr": "sum(pm2_process_status_launching{name=\"blue\"})",
     "legendFormat": "launching"
    },
    {
     "expr": "sum(pm2_process_status_stopped{name=\"blue\"})",
     "legendFormat": "stopped"
    },
    {
     "expr": "sum(pm2_process_status_errored{name=\"blue\"})",
     "legendFormat": "errored"
    }
   ]
  },
  {
   "title": "Memory Statistics for Default",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pm2_process_memory_array_buffers{name=\"default\"})/sum(pm2_processes{name=\"default\"})",
     "legendFormat": "array buffers"
    },
    {
     "expr": "sum(pm2_process_memory_external{name=\"default\"})/sum(pm2_processes{name=\"default\"})",
     "legendFormat": "external"
    },
    {
     "expr": "sum(pm2_process_memory_heap_used{name=\"default\"})/sum(pm2_processes{name=\"default\"})",
     "legendFormat": "heap used"
    },
    {
     "expr": "sum(pm2_process_memory_heap_total{name=\"default\"})/sum(pm2_processes{name=\"default\"})",
     "legendFormat": "heap total"
    },
    {
     "expr": "sum(pm2_process_memory_rss{name=\"default\"})/sum(pm2_processes{name=\"default\"})",
     "legendFormat": "rss"
    }
   ]
  },
  {
   "title": "Memory Statistics for Blue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pm2_process_memory_array_buffers{name=\"blue\"})/sum(pm2_processes{name=\"blue\"})",
     "legendFormat": "array buffers"
    },
    {
     "expr": "sum(pm2_process_memory_external{name=\"blue\"})/sum(pm2_processes{name=\"blue\"})",
     "legendFormat": "external"
    },
    {
     "expr": "sum(pm2_process_memory_heap_used{name=\"blue\"})/sum(pm2_processes{name=\"blue\"})",
     "legendFormat": "heap used"
    },
    {
     "expr": "sum(pm2_process_memory_heap_total{name=\"blue\"})/sum(pm2_processes{name=\"blue\"})",
     "legendFormat": "heap total"
    },
    {
     "expr": "sum(pm2_process_memory_rss{name=\"blue\"})/sum(pm2_processes{name=\"blue\"})",
     "legendFormat": "rss"
    }
   ]
  }
 ]
}